name: example
version: 7.0.4
description: >
  Just an example, not for publishing.
authors:
- Victor Heredia <victorevox@gmail.com>
homepage: https://github.com/victorevox/built_redux_navigation_middleware

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  flutter:
      sdk: flutter   
  built_collection: '>=2.0.0 <5.0.0'
  built_redux: ^7.5.8
  built_value: ^6.0.0
  built_redux_navigation_middleware:

dev_dependencies:
  build: ^1.2.1
  build_runner: ^1.6.0
  built_value_generator: ^6.0.0
  pedantic: ^1.4.0
  quiver: '>=0.21.0 <3.0.0'
  test: ^1.0.0

dependency_overrides:
  built_redux_navigation_middleware:
    path: ../